env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "global-require": 0,
  "import/no-dynamic-require": 0
}
